### ISSUE TITLE
Accessibility Release test pass on TSDoc on Web platform in May'23

### ISSUE THREAD

**Issue by vaishali1397** [microsoft/rushstack-websites#173]
https://github.com/microsoft/rushstack-websites/issues/166
https://github.com/microsoft/rushstack-websites/issues/167
https://github.com/microsoft/rushstack-websites/issues/171
https://github.com/microsoft/rushstack-websites/issues/172
https://github.com/microsoft/rushstack-websites/issues/170
https://github.com/microsoft/rushstack-websites/issues/169
https://github.com/microsoft/rushstack-websites/issues/168
https://github.com/microsoft/rushstack-websites/issues/157
https://github.com/microsoft/rushstack-websites/issues/155
https://github.com/microsoft/rushstack-websites/issues/154
https://github.com/microsoft/rushstack-websites/issues/153
https://github.com/microsoft/rushstack-websites/issues/151
https://github.com/microsoft/rushstack-websites/issues/148
https://github.com/microsoft/rushstack-websites/issues/147
https://github.com/microsoft/rushstack-websites/issues/146
https://github.com/microsoft/rushstack-websites/issues/145
https://github.com/microsoft/rushstack-websites/issues/144

**Comment by Raisul123** [comment]
Report Shared hence closing the Task
