### ISSUE TITLE
[rushjs.io] CORS error when using search bar on site

### ISSUE THREAD

**Issue by jasonbosco** [microsoft/rushstack-websites#234]
Steps to reproduce:

1. Go to https://rushjs.io
2. Click on the search bar on the top right and type in a search term
3. It does not return any results

Looking at the browser dev console, shows this CORS error:

![Screenshot 2024-05-22 at 1 56 07 PM](https://github.com/microsoft/rushstack-websites/assets/458383/cf2be986-8f37-4404-a1a2-d338746f7a2c)

I suspect that the Typesense Server powering the search needs to have CORS explicitly enabled as described [here](https://typesense.org/docs/26.0/api/server-configuration.html#cors).

**Comment by kenrick95** [comment]
This should be due to the Typesense Server being down. It should be already fixed, after notifying [Zulip chat](https://rushstack.zulipchat.com/#narrow/stream/311789-website-docs/topic/.E2.9C.94.20Search.20seems.20down.3F/near/440253067)

cc @octogonz

**Comment by octogonz** [comment]
Yes, this is resolved now. Thanks for reporting it!
