### ISSUE TITLE
Missing upcoming events.

### ISSUE THREAD

**Issue by halfnibble** [microsoft/rushstack-websites#26]
There should be events on 
- Feb 4th
- March 4th
- April 1st (April fools, lol)
- etc.

Right?

**Comment by octogonz** [comment]
Yes. Generally I like to include an agenda, but we can post them in advance and then update the event with the agenda later.

**Comment by octogonz** [comment]
The Feb 4th event is here BTW: https://rushstack.io/community/event/?id=11
