### ISSUE TITLE
Redirect to UPGRADING.md returns 404

### ISSUE THREAD

**Issue by robbyphillips** [microsoft/rushstack-websites#34]
The error message for running `rush build` with an outdated `<project>/config/rush-project.json` gives a link to https://rushjs.io/link/upgrading which currently returns a 404.

Also in [zulip](https://rushstack.zulipchat.com/#narrow/stream/262513-general/topic/Build.20cache.20.26.20rush-project.2Ejson)

**Comment by octogonz** [comment]
Thanks for reporting this!

**Comment by octogonz** [comment]
Looks like this was originally implemented for Jekyll in https://github.com/microsoft/rushjs.io-website/pull/119 but got lost in the migration to Docusaurus.

**Comment by octogonz** [comment]
Fixed in #36
