### ISSUE TITLE
Shell commands in documentation contains syntax errors

### ISSUE THREAD

**Issue by iampeterbanjo** [microsoft/rushstack-websites#42]
Hi, thank you for working on this project.

As a developer investigating using Rush on a project
And reading the documentation
I want to be able to follow the getting started instructions
In order to see Rush in action

Given the shell commands in the Rush documentation
For example `$ npm install -g @microsoft/rush`
When I copy and paste them into my terminal
I expect that the commands will work
But I encounter these errors
In fish shell (my main terminal)
> fish: Expected a variable name after this $

And in a Bash shell
> zsh: command not found: $

Operating system: Mac OS
Terminal: iTerm

**Comment by octogonz** [comment]
`$` is the stereotypical shell prompt. For example:

![image](https://user-images.githubusercontent.com/4673363/169738481-50722674-fb0f-4961-9889-e957190d2be6.png)


![image](https://user-images.githubusercontent.com/4673363/169738436-33473950-22e4-41dd-9aa9-6c4b409c7b9b.png)


You are not supposed to type that character.  We include it to distinguish typed inputs versus program outputs or comments, for example:

```bash
$ rush scan

Rush Multi-Project Build Tool 5.68.1 - https://rushjs.io
Node.js version is 14.17.0 (LTS)

Starting "rush scan"

ERROR: You must run "rush scan" in a project folder containing a package.json
file.
```

**Comment by octogonz** [comment]
Looking at some other documentation websites though, it is common to omit the `$`.



`docs.microsoft.com` uses separate boxes for inputs/outputs:

https://docs.microsoft.com/en-us/learn/modules/bash-introduction/3-bash-commands

<kbd><img src="https://user-images.githubusercontent.com/4673363/169739188-c5f5b42d-ea04-49ac-b96f-6c551934ad7b.png" /></kbd>

`ubuntu.com` uses screenshots when they need to show outputs:

https://ubuntu.com/tutorials/command-line-for-beginners#5-moving-and-manipulating-files

<kbd><img src="https://user-images.githubusercontent.com/4673363/169739128-fc7b49c1-dc29-4aa9-a11c-d9d71fd13870.png" /></kbd>

🤔Maybe we can improve this.

**Comment by iampeterbanjo** [comment]
Thank you for taking such a detailed comparison with other approaches. I'm familiar with `$` , `>` and other hints for the terminal but I believe we can have a better DX. For example, after seeing the first error I understood that I had to -

- re-paste the command in the terminal
- go back to the start of the command
- remove $ 

And repeat this for every command. Even with terminal shortcuts and history, there are still additional steps to using the docs.

**Comment by octogonz** [comment]
Okay, @iampeterbanjo you have persuaded me. 😁  Fixed in https://github.com/microsoft/rushstack-websites/pull/87
