### ISSUE TITLE
Travis CI is sadly not what it was before maybe it should be removed

### ISSUE THREAD

**Issue by Luxcium** [microsoft/rushstack-websites#99]
I suggest that you remove the [Travis CI](https://travis-ci.com/) config file as it is now an expensive product that cost 69$ per month or more...

Your documentation examples could show how to use Azure DevOps Services CI/CD or other third parties examples, some are suggested by _Adam Gordon Bell_ in the [blog link](https://earthly.dev/blog/migrating-from-travis/) below: 

> January 7, 2021 · Many open-source projects are still using Travis and open-source maintainers are notoriously overworked.  Time spent migrating builds is time not spent on other things.  Large well-maintained projects will likely quickly transition but for many smaller projects, an abrupt change in a service they depend on is a huge challenge.
― Adam Gordon Bell https://earthly.dev/blog/migrating-from-travis/ 

## Azure DevOps Services

When you sign up for Azure DevOps, you get the following tier of free services:

 - First five users free (Basic license)
 - Azure Pipelines:
    - One [Microsoft-hosted CI/CD](https://learn.microsoft.com/fr-fr/azure/devops/pipelines/licensing/concurrent-jobs?view=azure-devops#how-much-do-parallel-jobs-cost) (one concurrent job, up to 30 hours per month)
    - One self-hosted CI/CD concurrent job
 - Azure Boards: Work item tracking and Kanban boards
 - Azure Repos: Unlimited private Git repos
 - Azure Artifacts: Two GiB free per organization

###### ― Maybe duplicate of [rushstack #3646](https://github.com/microsoft/rushstack/issues/3646)

**Comment by octogonz** [comment]
I agree 👍

**Comment by octogonz** [comment]
Fixed in https://github.com/microsoft/rushstack-websites/pull/105
